pagopa/p4pa-pu-fe

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/pr-title.yml
Mod pipelines useful for the first tasks
=> Mod pipelines useful for the first tasks

src/vite-env.d.ts, vite.config.ts
This PR add the support of the subpath also in the dev server (vite). 
- add env variable also in viteconfig
enhance the DX
=> chore: [P4ADEV-1477] Manage subpath on the dev server

eslint.config.js, src/App.tsx, src/components/Header/index.tsx, src/components/layout/Layout.tsx, src/main.tsx, src/models/Breadcrumbs.ts, src/routes/Home/index.tsx, src/routes/routes.ts, src/utils/theme.tsx, vite.config.ts
Setup the main header with party-selection.
- add main header
- set a mock response to party selection
First header setup according to the design
=> feat: [P4ADEV-1565] Main Header

src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarMenuItem.tsx, src/components/Sidebar/sidebar.styles.ts, src/main.tsx, src/models/SidebarMenuItem.ts, src/translations/it/translations.json
According to the P&D, it's necessary to have a sidebar that "collapse" when the hambuger con is clicked
- add collapse funcionality
- cosmetic fixes
- add translations for the sidebar
Collapse the sidebar
=> feat: [P4ADEV-1569] Add hamburger functionality

.gitignore, package.json, ts-to-zod.config.cjs
This PR adds the swagger definition and the auto-gen feature
- add swagger to package.json
- create custom command to _generate_ the clients and schemas 
- add the conversion from ts to Zod
In this way we obtain _automatically_ the client and schema for the services calls
=> feat: [P4ADEV-1695] Integrate swagger and autogeneration

src/main.tsx
This PR add the wrapper to the main file.
With this, now, we can set services calls.
=> feat: [P4ADEV-1696] Add React Query to the main app

vite.config.ts
This PR set the target build with `es2020` as requested by Vite 
- set target
=> feat: [P4ADEV-1847] build target

package.json
=> hotfix: Update build command

package.json, src/App.tsx, src/components/FlowDataGrid/CustomDataGrid.tsx, src/components/FlowDataGrid/FlowDataGrid.tsx, src/components/TelematicReceipt/TelematicReceipt.tsx, src/components/TelematicReceiptFlowExportOverview/TelematicReceiptFlowExportOverview.tsx, src/components/TelematicReceiptFlowExportOverview/index.tsx, src/routes/TelematicReceiptFlowExportOverview/index.tsx, src/routes/routes.ts, src/translations/it/translations.json, yarn.lock
Added telematic receipts flow export page
=> feat: [P4ADEV-1817] export telematic receipts static UI

src/utils/style.tsx
This PR fix a button border stroke dropping a style override
- drop style override
Align FE with the design
=> feat: [P4ADEV-1898] Button border

src/App.tsx, src/components/TelematicReceiptExportFlowReservation/TelematicReceiptExportFlowReservation.tsx, src/components/TelematicReceiptExportFlowThankYouPage/TelematicReceiptExportFlowThankYouPage.tsx, src/components/TelematicReceiptExportFlowThankYouPage/index.tsx, src/components/ThankYouPage/ThankYouPage.tsx, src/routes/TelematicReceiptExportFlowThankYouPage/index.tsx, src/routes/routes.ts, src/translations/it/translations.json
Added telematic receipt export flow thank you page
=> feat: [P4ADEV-1819] export flow thank you page

src/components/ActionMenu/ActionMenu.tsx, src/components/Drawer/CustomDrawer.tsx, src/components/TelematicReceiptFlowExportOverview/TelematicReceiptFlowExportOverview.tsx, src/components/TelematicReceiptSearchResults/SearchResultsDataGrid.tsx, src/components/TelematicReceiptSearchResults/TelematicReceiptSearchResults.tsx, src/translations/it/translations.json
Add Detail Drawer and fixed resize in DataGrid Pages
=> feat: [P4ADEV-1771] detail drawer

.github/workflows/lint.yml, eslint.config.js
This PR adds lint check as pipeline
=> ci: [P4ADEV-1948] lint pipeline

src/App.tsx, src/components/ActionMenu/ActionMenu.tsx, src/components/TelematicReceipt/TelematicReceipt.tsx, src/components/TelematicReceiptImportFlowOverview/FilterContainer.tsx, src/components/TelematicReceiptImportFlowOverview/TelematicReceiptImportFlowOverview.tsx, src/components/TelematicReceiptImportFlowOverview/index.tsx, src/components/TelematicReceiptSearchResults/SearchResultsDataGrid.tsx, src/routes/TelematicReceiptImportFlowOverview/index.test.tsx, src/routes/TelematicReceiptImportFlowOverview/index.tsx, src/routes/routes.ts, src/store/types.ts, src/translations/it/translations.json
=> feat: [P4ADEV-1820] import flow overview

package.json, src/api/brokers.ts, src/hooks/useFeConfig.test.ts, src/hooks/useFeConfig.tsx, src/store/AppStateStore.test.ts, src/store/AppStateStore.ts, src/store/GlobalStore.test.tsx, src/store/GlobalStore.tsx, yarn.lock
- AppState signal is called via StoreContext
- removes unused functions
- broker config api has a retry count of 2
- udpdates test and removes mocking where possible
- fixes a test error log
signal value change was not triggering a rerender 
- unit test
=> feat: [P4ADEV-1982] broker config retry

src/App.tsx, src/components/FileUploader/FileUploader.test.tsx, src/components/FileUploader/FileUploader.tsx, src/components/TelematicReceipt/TelematicReceipt.tsx, src/components/TelematicReceiptFlowImport/TelematicReceiptFlowImport.tsx, src/components/TelematicReceiptFlowImport/TelematicReceiptFlowImportThankYouPage.tsx, src/components/TelematicReceiptImportFlowOverview/TelematicReceiptImportFlowOverview.tsx, src/routes/TelematicReceiptFlowImport/index.test.tsx, src/routes/TelematicReceiptFlowImport/index.tsx, src/routes/TelematicReceiptFlowImportThankYouPage/index.test.tsx, src/routes/TelematicReceiptFlowImportThankYouPage/index.tsx, src/routes/TelematicReceiptImportFlowOverview/index.test.tsx, src/routes/routes.ts, src/translations/it/translations.json, src/utils/__tests__/filevalidation.test.tsx, src/utils/filevalidation.tsx, yarn.lock
- creation flow upload page
- creation of upload file component
- creation of thank you page for successful upload
- add redirect to import page from import overview page
- unit testing (only render)
=> feat: [P4ADEV-1821] flow upload pages

src/App.tsx, src/components/TelematicReceiptDetail/DetailContainer.tsx, src/components/TelematicReceiptDetail/TelematicReceiptDetail.tsx, src/components/TelematicReceiptDetail/index.tsx, src/components/TelematicReceiptSearchResults/SearchResultsDataGrid.tsx, src/routes/TelematicReceiptDetail/index.test.tsx, src/routes/TelematicReceiptDetail/index.tsx, src/routes/routes.ts, src/translations/it/translations.json
add telematic receipt detail page
=> feat: [P4ADEV-1977] telematic receipt detail

package.json, src/components/Footer/index.tsx, src/components/Markdown/index.tsx, src/components/Markdown/markdown.test.tsx, src/translations/it/translations.json, yarn.lock
- adds a markdown rendering component
- markdown only accepts some syntax
- footer uses markdown
- adds react-remark and rehype
- added footer info fallback to translations
- unit tests
Footer legal info needs to be rendered from the backend with styling informations. react-remark with rehype seems to be the safest and more robus option.
- unit tests
=> feat: [P4ADEV-1984] footer markdown

src/App.tsx, src/components/Reporting/Reporting.tsx, src/components/Reporting/index.tsx, src/components/SearchButton/index.tsx, src/components/SearchCard/SearchCard.tsx, src/components/Sidebar/Sidebar.tsx, src/components/TelematicReceipt/TelematicReceipt.tsx, src/routes/Reporting/index.test.tsx, src/routes/Reporting/index.tsx, src/routes/routes.ts, src/translations/it/translations.json
=> feat: [P4ADEV-1955] reporting overview

src/components/TelematicReceipt/TelematicReceipt.tsx, src/components/TelematicReceiptDetail/TelematicReceiptDetail.tsx, src/components/TelematicReceiptExportFlowReservation/TelematicReceiptExportFlowReservation.tsx, src/components/TelematicReceiptFlowExportOverview/TelematicReceiptFlowExportOverview.tsx, src/components/TelematicReceiptFlowImport/TelematicReceiptFlowImport.tsx, src/components/TelematicReceiptImportFlowOverview/TelematicReceiptImportFlowOverview.tsx, src/components/TelematicReceiptSearchResults/TelematicReceiptSearchResults.tsx, src/components/TitleComponent/TitleComponent.test.tsx, src/components/TitleComponent/TitleComponent.tsx, src/routes/TelematicReceiptSearchResults/index.test.tsx
- Creation of TitleComponent
- Replaced title with TitleComponent on each page
- code duplication and uniformity
- unit tests
=> feat: [P4ADEV-1899] title component

src/utils/style.tsx
=> fix: [P4ADEV-1898] drop override

src/App.tsx, src/components/BackButton/index.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/FileUploader/FileUploader.test.tsx, src/components/FileUploader/FileUploader.tsx, src/components/FlowDataGrid/FlowDataGrid.tsx, src/components/Footer/index.tsx, src/components/Sidebar/Sidebar.tsx, src/components/TelematicReceipt/TelematicReceipt.tsx, src/components/TelematicReceiptExportFlowReservation/TelematicReceiptExportFlowReservation.tsx, src/components/TelematicReceiptExportFlowThankYouPage/TelematicReceiptExportFlowThankYouPage.tsx, src/components/TelematicReceiptFlowExportOverview/TelematicReceiptFlowExportOverview.tsx, src/components/TelematicReceiptFlowImport/TelematicReceiptFlowImport.tsx, src/components/TelematicReceiptFlowImport/TelematicReceiptFlowImportThankYouPage.tsx, src/components/TelematicReceiptImportFlowOverview/TelematicReceiptImportFlowOverview.tsx, src/components/TelematicReceiptSearchResults/SearchResultsDataGrid.tsx, src/components/TelematicReceiptSearchResults/TelematicReceiptSearchResults.tsx, src/translations/i18n.ts, src/translations/it/translations.json
This PR refact the translation's file trying to normalize strings. Consequently some tsx files has been modified according the new setup.
- Translations
- All tsx pages
Normalize & optimize translations
=> feat: [P4ADEV-1954] Refact translations

src/components/ReportingDetail/ReportingDetail.tsx, src/components/ReportingImportFlowOverview/ReportingImportFlowOverview.tsx, src/components/ReportingSearchResults/ReportingSearchResults.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/sidebar.styles.ts, src/components/TelematicReceiptFlowExportOverview/TelematicReceiptFlowExportOverview.tsx, src/components/TelematicReceiptImportFlowOverview/TelematicReceiptImportFlowOverview.tsx, src/components/TelematicReceiptSearchResults/TelematicReceiptSearchResults.tsx, src/components/layout/Layout.tsx
This PR try to fix the main layout to avoid the use of "position absolute" when there is a Datagrid component.
- drop position absolute from pages
- refact the Layout component using the Grid attribute instead floating
- modify the Sidebar style's using a proper attribute and discard explicit width
Avoid the use of position absolute
- visual test
=> feat: [P4ADEV-1979] Refact layout

src/App.tsx, src/components/FilterContainer/FilterContainer.tsx, src/components/Treasury/Treasury.tsx, src/components/TreasuryImportFlowOverview/TreasuryImportFlowOverview.tsx, src/components/TreasuryImportFlowOverview/index.tsx, src/routes/TreasuryImportFlowOverview/index.test.tsx, src/routes/TreasuryImportFlowOverview/index.tsx, src/routes/routes.ts, src/translations/it/translations.json
- Added Treasury imported flows overview (removed wrap Boxes).
- Fixed FilterContainer's select: now it properly selects the value.
- unit tests
=> feat: [P4ADEV-2010] treasury imported flows overview

src/components/Footer/Footer.test.tsx, src/components/Footer/index.tsx, src/components/layout/Layout.tsx, src/hooks/useFooterData.test.tsx, src/hooks/useFooterData.tsx, src/models/Links.ts
Adds a simplified mui-italia footer which supports custum logo
- Rewrite Footer component
- useFooterData hooks
- unit tests
Making the mui-italia footer logo customizable is not possible at the present moment.
- unit tests
=> feat: [P4ADEV-1983] custom footer with logo
